version: "3.9"

services:
  db:
    container_name: benchmark-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: Passw0rd123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: